steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      [
        "--context=.",
        "--dockerfile=Dockerfile",
        "--destination=gcr.io/$PROJECT_ID/backend:latest",
        "--cache=true",
        "--cache-ttl=168h"
      ]

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100

# Built images
images:
  - gcr.io/$PROJECT_ID/backend:latest

# Optional: Add tags for better organization
tags:
  - backend
  - python