services:
  redis:
    image: redis:7-alpine
    container_name: hireview-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    container_name: hireview-backend
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - us-central1-docker.pkg.dev/hireview-prep-470120/cloud-run-source-deploy/backend-app:latest
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - FACE_MESH_EVERY=2
      - EMOTION_EVERY=10
      - NUM_WORKERS=1
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT=hireview-prep-470120
      - TARGET_SERVICE_ACCOUNT=916307297241-compute@developer.gserviceaccount.com
    volumes:
      - ${HOME}/.config/gcloud:/root/.config/gcloud:ro
    platform: linux/amd64
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --no-access-log --log-level info
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:


